name: h2of
dag:
  harmor:
    config:
      _target_: diffsynth.modules.generators.Additive
      sample_rate: ${sample_rate}
      normalize_below_nyquist: true
      n_harmonics: 256
    connections:
      amplitudes: AMP
      harmonic_distribution: HARM
      f0_hz: f0
  filtnoise:
    config:
      _target_: diffsynth.modules.generators.FilteredNoise
      filter_size: 257
    connections:
      freq_response: FREQRES
  add:
    config:
      _target_: diffsynth.processor.Add
    connections:
      signal_a: harmor
      signal_b: filtnoise
fixed_params:
  f0: null # f0 conditioning
static_params: null