# Harmonic + noise model -> IR reverb
name: hpnir
dag:
  harmonic:
    config:
      _target_: diffsynth.modules.generators.Harmonic
      sample_rate: ${sample_rate}
      normalize_below_nyquist: true
      n_harmonics: 256
    connections:
      amplitudes: AMP
      harmonic_distribution: HARM
      f0_hz: f0
  filtnoise:
    config:
      _target_: diffsynth.modules.generators.FilteredNoise
      filter_size: 512
    connections:
      freq_response: FREQRES
  add:
    config:
      _target_: diffsynth.processor.Add
    connections:
      signal_a: harmonic
      signal_b: filtnoise
  irreverb:
    config:
      _target_: diffsynth.modules.reverb.IRReverb
    connections:
      audio: add
conditioned: [f0,]