# Harmonic + noise model -> IR reverb
name: hpnir
# Parameter to be estimated externally:
# AMP, HARM, FREQRES
dag:
  harmonic:
    config:
      _target_: diffsynth.modules.generators.Harmonic
      sample_rate: ${sample_rate}
      normalize_below_nyquist: true
      n_harmonics: 256
    connections:
      amplitudes: AMP
      harmonic_distribution: HARM
      f0_hz: f0
  filtnoise:
    config:
      _target_: diffsynth.modules.generators.FilteredNoise
      filter_size: 512
    connections:
      freq_response: FREQRES
  add:
    config:
      _target_: diffsynth.processor.Add
    connections:
      # adds together the outputs from harmonic and filtered noise
      signal_a: harmonic
      signal_b: filtnoise
  irreverb:
    config:
      _target_: diffsynth.modules.reverb.IRReverb
    connections:
      # Uses the output from "add" module as input
      audio: add
# Parameters that are conditioned (precomputed)
conditioned: [f0,]