# Harmonic + noise model -> IR reverb
name: hpnirmix
dag:
  harmonic:
    config:
      _target_: diffsynth.modules.generators.Harmonic
      sample_rate: ${sample_rate}
      normalize_below_nyquist: true
      n_harmonics: 256
    connections:
      amplitudes: AMP
      harmonic_distribution: HARM
      f0_hz: f0
  filtnoise:
    config:
      _target_: diffsynth.modules.generators.FilteredNoise
      filter_size: 512
    connections:
      freq_response: FREQRES
  mixhn:
    config:
      _target_: diffsynth.processor.Mix
    connections:
      signal_a: harmonic
      signal_b: filtnoise
      mix_a: harm_mix
      mix_b: noise_mix
  irreverb:
    config:
      _target_: diffsynth.modules.reverb.IRReverbMix
    connections:
      audio: mixhn
      mix: irmix
conditioned: [f0, harm_mix, noise_mix, irmix]