# @package _global_

defaults:
  - _self_
  - trainer: default.yaml
  - model: default.yaml
  - data: slice.yaml
  - synth: hpnir.yaml
  - loss: spectral.yaml
  - exp: null
  - optuna: null

name: null
sample_rate: 48000
ckpt_nepochs: null
ckpt_nsteps: 10000
batch_size: 16
seed: 0
num_workers: 8
ckpt: null # Used for resuming from checkpoint

data:
  f0_range: [32, 2000]

trainer:
  check_val_every_n_epoch: 10
  # Max iterations
  max_steps: 100000

# Output directory
hydra:
  job:
    chdir: true
  run:
    dir: logs/${name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: logs/${name}/multirun_${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}

# name of stat to use as monitor for optuna multirun
# ex.) "val_0/lsd" - LSD of 0th validation dataset
monitor: "val_0/lsd"