# @package _global_

defaults:
  - _self_
  - trainer: default.yaml
  - model: default.yaml
  - data: slice.yaml
  - synth: hpnir.yaml
  - loss: spectral.yaml
  - exp: null
  - optuna: null

# name of stat to use as monitor 
# ex.) "val_0/lsd" - LSD of 0th validation dataset
name: null
sample_rate: 48000
monitor: "val_0/lsd"
ckpt_nepochs: null
ckpt_nsteps: 10000
batch_size: 16
seed: 0
ckpt: null

trainer:
  check_val_every_n_epoch: 10
hydra:
  job:
    chdir: true
  run:
    dir: logs/${name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: logs/${name}/multirun_${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}

data:
  f0_range: [32, 2000]